plugins {
    alias libs.plugins.android.application
    alias libs.plugins.navigation.safe.args
}

android {
    namespace 'com.kaisar.xposed.godmode'
    compileSdk 35
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.viewblocker.jrsen"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 40
        versionName "5.4.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        vectorDrawables.useSupportLibrary = true
    }
    buildFeatures {
        buildConfig = true
        aidl = true
    }
    androidResources {
        additionalParameters("--allow-reserved-package-id", "--package-id", "0x95")
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(path: ':engine')
    implementation project(path: ':libxservicemanager')
    implementation libs.androidx.constraintlayout
    implementation libs.bundles.navigation
    androidTestImplementation(libs.espresso.core) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    implementation libs.androidx.appcompat
    implementation libs.androidx.viewpager2
    implementation libs.androidx.fragment
    implementation libs.androidx.preference
    compileOnly fileTree(include: ['*.jar'], dir: 'src/main/lib')
    implementation libs.gson
    implementation libs.material
    implementation libs.glide
    implementation libs.rikka.insets
    annotationProcessor libs.glide.compiler
}
